services:
  app:
    image: hoheesu/nestjs-app:latest
    env_file:
      - .env
    ports:
      - '8080:3000'
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    environment:
      PORT: ${PORT}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ['npm', 'run', 'start:dev']
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LC_ALL: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass strongpassword --port 6379 --appendonly yes
    labels:
      - 'name=redis'
      - 'mode=standalone'
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'strongpassword', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  redis-data:
