services:
  app:
    image: hoheesu/nestjs-app:latest
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm', 'run', 'start']
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      LC_ALL: C.UTF-8
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass strongpassword --port 6379 --appendonly yes
    labels:
      - 'name=redis'
      - 'mode=standalone'
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'strongpassword', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  redis-data:
