name: Docker CI/CD Pipeline

# 워크플로우 실행 트리거 설정
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    name: Docker Workflow
    runs-on: ubuntu-latest # GitHub Actions 실행 환경

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest

  deploy:
    name: Deploy to Server
    needs: build-and-push # build-and-push 작업이 성공하면 실행
    runs-on: ubuntu-latest

    steps:
      # 1. SSH 키 권한 설정
      - name: Configure SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # 2. 서버에 SSH로 접속하고 파일 복사
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/home/${{ secrets.SERVER_USER }}/app'

      # 3. 서버에서 Docker 컨테이너 실행
      - name: Run Docker Container on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest
            docker stop nestjs-container || true
            docker rm nestjs-container || true
            docker run -d --name nestjs-container -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest

      # 4. Docker 컨테이너 상태 확인
      - name: Check Docker Container Status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker ps -a | grep nestjs-container
